version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lottery_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initrd.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: